repos:
    - repo: local
      hooks:
          - id: flakehell
            name: flakehell
            entry: poetry run flakehell lint
            types: [python]
            language: system
            stages: [push, commit]
          - id: mypy
            name: mypy
            entry: poetry run mypy
            types: [python]
            language: system
            stages: [push, commit]
          - id: pytest
            name: pytest
            entry: poetry run pytest
            types: [python]
            language: system
            pass_filenames: false
            always_run: true
            stages: [push, commit]
