repos:
    - repo: local
      hooks:
          - id: flakehell
            name: flakehell
            entry: flakehell lint
            types: [python]
            language: python
            stages: [push, commit]
          - id: mypy
            name: mypy
            entry: mypy
            types: [python]
            language: python
            stages: [push, commit]
          - id: pytest
            name: pytest
            entry: pytest
            types: [python]
            language: python
            pass_filenames: false
            always_run: true
            stages: [push, commit]
