name: Checks

on: [push, pull_request]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Setup poetry
              uses: abatilo/actions-poetry@v2

            - name: Cache
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pypoetry/virtualenvs
                  key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-poetry-

            - name: Install requirements
              run: poetry install --no-root

            - name: Lint
              run: poetry run flakehell lint

            - name: Type check
              run: poetry run mypy .

            - name: Run tests
              run: poetry run pytest .
